export const HEATING = {
  giorno: {
    label: "Zona Giorno",
    request: "binary_sensor.richiesta_pompa_giorno",
    mandata: "sensor.temperatura_rtd_1",
    ritorno: "sensor.temperatura_rtd_2",
    valve: "sensor.apertura_mix_giorno",
    setpointInv: "number.setpoint_invernale_giorno",
    setpointEst: "number.setpoint_estivo_giorno",
    prop: "number.proporzionale_giorno",
    integ: "number.integrale_giorno",
    manualSwitch: "switch.manuale_mix_giorno",
    manualValue: "number.valore_manuale_giorno",
  },
  notte: {
    label: "Zona Notte",
    request: "binary_sensor.richiesta_pompa_notte",
    mandata: "sensor.temperatura_rtd_3",
    ritorno: "sensor.temperatura_rtd_4",
    valve: "sensor.apertura_mix_notte",
    setpointInv: "number.setpoint_invernale_notte",
    setpointEst: "number.setpoint_estivo_notte",
    prop: "number.proporzionale_notte",
    integ: "number.integrale_notte",
    manualSwitch: "switch.manuale_mix_notte",
    manualValue: "number.valore_manuale_notte",
  },
  pdc: {
    label: "PDC",
    request: "binary_sensor.richiesta_pompa_vmc",
    mandata: "sensor.temperatura_mandata_pdc",
    ritorno: "sensor.temperatura_ritorno_pdc",
    acs: "sensor.temperatura_acs_pdc",
    esterna: "sensor.temperatura_esterna_pdc",
    stagione: "select.stagione",
  },
  vmc: {
    label: "VMC",
    request: "binary_sensor.richiesta_pompa_vmc",
    mandata: "sensor.temperatura_rtd_5",
    ritorno: "sensor.temperatura_rtd_6",
  },
  ricircolo: {
    label: "Ricircolo",
    request: "binary_sensor.richiesta_pompa_ricircolo",
    temp: "sensor.temperatura_rtd_7",
    enable: "switch.abilitazione_ricircolo",
    tOn: "number.tempo_on_ricircolo",
    tOff: "number.tempo_off_ricircolo",
  },
};
